#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# copyright: 2010 to the present, california institute of technology.
# all rights reserved. united states government sponsorship acknowledged.
# any commercial use must be negotiated with the office of technology transfer
# at the california institute of technology.
# 
# this software may be subject to u.s. export control laws. by accepting this
# software, the user agrees to comply with all applicable u.s. export laws and
# regulations. user has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# installation and use of this software is restricted by a license agreement
# between the licensee and the california institute of technology. it is the
# user's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envresamp')
package = envresamp['PACKAGE']
project = envresamp['PROJECT']
install = envresamp['PRJ_SCONS_INSTALL'] + '/' + package + '/' + project
build = envresamp['PRJ_SCONS_BUILD'] + '/' + package + '/' + project
libList = ['gomp','resamp','resampLib','DataAccessor','InterleavedAccessor','utilLib','StdOEL']
envresamp.PrependUnique(LIBS = libList)
module = envresamp.LoadableModule(target = 'resamp.abi3.so', source = 'resampmodule.cpp') 
envresamp.Install(install,module)
envresamp.Alias('install',install)
envresamp.Install(build,module)
envresamp.Alias('build',build)
